name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: |
        sudo apt update;
        sudo apt install git make ruby gem squashfs-tools
        wget https://golang.org/dl/go1.19.linux-amd64.tar.gz -O /tmp/golang1.19.tar.gz
        tar --transform=s,go,go1.19, -zxf /tmp/golang1.19.tar.gz
        rm -rf /usr/local/go*
        sudo mv go1.19 /usr/local/
        sudo ln -fs /usr/local/go1.19 /usr/local/go
        sudo ln -fs /usr/local/go/bin/go /usr/bin/go
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install nfpm

    - name: Make
      run: make build-bins
      
    - name: mkdir
      run:  mkdir -p packages

    - name: Build rpm
      run: nfpm pkg --packager rpm --target ./packages

    - name: Build deb
      run: nfpm pkg --packager deb --target ./packages
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: DEB
        path: packages/*.deb
        
    - name: Upload RPM
      uses: actions/upload-artifact@v3.1.2
      with:
        name: project-binary
        path: packages/*.rpm
    - name: Download Binary
      uses: actions/download-artifact@v1
      with:
        name: project-binary

